# Generated by Django 4.2 on 2023-12-11 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title')),
                ('permissions', models.IntegerField(verbose_name='Permissions')),
            ],
            options={
                'db_table': 'auth"."roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('third_party_id', models.CharField(max_length=128, verbose_name='Third party id')),
                ('third_party_title', models.CharField(max_length=50, verbose_name='Third party title')),
            ],
            options={
                'verbose_name': 'Third party user',
                'verbose_name_plural': 'Third party users',
                'db_table': 'auth"."third_party_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Last name')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
            ],
            options={
                'db_table': 'auth"."users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth"."users_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=128, verbose_name='Source')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='Login time')),
            ],
            options={
                'verbose_name': 'User history',
                'verbose_name_plural': 'Users history',
                'db_table': 'auth"."users_history',
                'managed': False,
            },
        ),
    ]
